#set_digital_output(1, ON) # 컨트롤러 신호 제어
#set_tool_digital_output(1, ON) #플랜지 신호 제어
#set_digital_output(2, ON)
#set_digital_output(2, OFF)
#set_digital_output(1)
#set_digital_output(-2)
#set_digital_output(2)
#set_digital_output(3)
#set_digital_output(4)
#set_digital_output(5)
set_digital_outputs([-1, -2, -3, -4, -5])
#mission1
def grip():
    set_digital_outputs([-1, -2, -3, -4, -5])
    wait(2)
    set_digital_output([2])
    wait(2)
    set_digital_output([-2])

def ungrip():
    set_digital_outputs([-1,-2,-3,-4,-5])
    wait(2)
    set_digital_output(4)
    wait(2)
    set_digital_output(-4)

def order(user):
    if user == 'open':
        grip()
    elif user == 'close':
        ungrip()

user = tp_get_user_input("what is your od?", input_type=DR_VAR_STR)
order(user)